# pylint: skip-file

samples = [
    "Do you watch anime ? if yes, whats your favourite one ? else, start with death note",
    "I love cold coffee and icecreams, but cold coffee is overpriced, everything in cafes is overpriced",
    "You should listen to 'Astrid S', especially 'Think Before I talk',she looks pretty with her blonde hair and blue eyes",
    "Thinking of some randome string all of a sudden is not so easy, takes me a while to think of something",
    "I figured that out just now. I waste almost 6 hours per day (most of it is wasted on classes)",
    "Did you listen to Ocean Eyes by Billie Eilish (Remix by Black Bear) ?, I've been watching you for sometime...",
    "Switch to discord man, stop using whatsapp, grow up, discord has much superior and cleaner",
    "If it is not documented or recorded, it never existed, so always push your code to git, learnt it after I lost the code for almost 5 projects",
    "Its windy today, perfect ! I love this weather, but theres a lot on the plate to do",
    "Would be super cool if we had no attendace policy, I would not attend a single class if that was true",
    "Most of the classes are boring, Idk why we have some of the classes (can't mention the name here)",
    "You should try cold coffee at JJ cafe and also the big bite burger, be it veg or non veg both are pretty good",
    "I want to get a machine gun, though I can't even lift it, lol, would also love to have a weapon arsenal",
    "Did you play Boom Beach ? or Clash of clans or Brawl stars or any super cell games ? if no, dude where did you come from Mars ?",
    "Video games are fun, you should try 'The finals on steam', I love that game, probably the best I ever played. up until now",
    "The finals was in beta stage, now its closed, gotta wait till December to play it, can't wait, I hope they don't delete old beta accounts",
    "5 Seconds of Summer - teeth, one of my favourites, YoungBlood, you should also listen to Vamps ",
    "Saurabhs discord id is xorcyan, idk why I am mentioning this, maybe I am out of ideas to write text",
    "Nope this text has no clue embedded into it, absolutely no clue, I am not joking or trying to confuse you, I just mentioned it",
    "I should learn C++, shsh.. theres a lot on the list to do, but I am so lazy to do, why am I so lazy ?",
    "Why am I so lazy ? its like, laziness is engrained in my DNA, if laziness was a person, I would probably be his/her father",
    "People with blue eyes and blonde hair look are rare, wish I had deep blue eyes, greeb eyes and red hair also pretty rare",
    "Never mind majority of these sentences are random, I'm just bored and I am typing anything thats meaningful",
    "Delete instagram asap, you could get addicted to reels, hits all of your dopamine centers, check your avg usage time",
    "I can win the gold medal in olympics under the field of procastination (if there's such a field), or maybe something beyond gold, like rank -infinity (beyond rank 1)",
    "Every programming language is tool in your tool box, nothing is superior to the other, you don't use python for high performance",
    "You cannot use a hammer where screw driver is needed, now don't tell me you would hammer the screw in.",
    "Use dark theme, idk how people manage to not burn their eyes wit the light theme, you should try ayu dark on VS code, I love that theme",
    "Stop using windows, switch to linux, if you want to play video games, some one took windows 11, removed all the bloatware and stuff that tracks you, and named it 'windows 11 tiny'",
    "Guess what ? someone developed a framework 'Micropython', so we can write code for microcontrollers in python, and here I am trying to write Hello world code",
    "Raspberry pi is overpriced, its performance sucks, would be cool, if I can just connect it to my laptop with a cable and access the file system, add files and run them..",
    "'God was a girl, the devil wore a tshirt', idk what Machine gun kelly meant by this line in the song 'love race'",
    "Gotta go to lunch, but I want to skip it, but I can't as I have already skipped my breakfast, btw ARM architecture is pretty cool, atleast I feel so",
    "What do you prefer using discord or whatsapp, i prefer discord",
]
